name: sfpython
channels:
- !!python/unicode
  'defaults'
dependencies:
- python=3.6
- pip>=9.0
- numpy>=1.12
- matplotlib>=2.0
- scikit-learn>=0.18
- scipy>=0.18
- pandas>=0.19
- pip:
  - tensorflow>=1.0
  - keras>=2.0